// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ids.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Aegis.Ids {

  /// <summary>Holder for reflection information generated from ids.proto</summary>
  public static partial class IdsReflection {

    #region Descriptor
    /// <summary>File descriptor for ids.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static IdsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CglpZHMucHJvdG8SCWFlZ2lzLmlkcyqJBAoFTXNnSUQSCwoHVU5LTk9XThAA",
            "EhEKDENTX0xPR0lOX1JFURDpBxIRCgxTQ19MT0dJTl9SRVMQ6gcSGAoTQzJT",
            "X0NSRUFURV9DQU1QX1JFURDNCBIYChNTMkNfQ1JFQVRFX0NBTVBfUkVTEM4I",
            "EhYKEUMyU19KT0lOX0NBTVBfUkVREM8IEhYKEVMyQ19KT0lOX0NBTVBfUkVT",
            "ENAIEhYKEVMyQ19DQU1QX1NOQVBTSE9UENEIEhwKF0MyU19RVUVSWV9DQU1Q",
            "X0xJU1RfUkVRENIIEhwKF1MyQ19RVUVSWV9DQU1QX0xJU1RfUkVTENMIEgwK",
            "B0NTX1BJTkcQ0Q8SDAoHU0NfUE9ORxDSDxIQCgtDU19NT1ZFX1JFURDTDxIQ",
            "CgtTQ19NT1ZFX05URhDUDxISCg1TQ19FTlRFUl9WSUVXENUPEhIKDVNDX0xF",
            "QVZFX1ZJRVcQ1g8SGAoTQ1NfVVBEQVRFX1NUQVRFX1JFURDXDxIaChVTQ19T",
            "VEFURV9VUERBVEVfQkFUQ0gQ2A8SFgoRU0NfTU9WRV9OVEZfQkFUQ0gQ2Q8S",
            "FgoRQ1NfU0tJTExfQ0FTVF9SRVEQ2g8SEgoNU0NfREFNQUdFX05URhDbDxIX",
            "ChJTU19DUkVBVEVfUk9PTV9SRVEQuRcSGgoVU1NfVEVSTUlOQVRFX1JPT01f",
            "UkVRELoXQjJaMGdpdGh1Yi5jb20vRmlsbHBlZC03MjYvQWVnaXNFbmdpbmUv",
            "c2hhcmVkL3BiL2lkc2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Aegis.Ids.MsgID), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum MsgID {
    [pbr::OriginalName("UNKNOWN")] Unknown = 0,
    /// <summary>
    /// 1000-1999: Lobby / Login
    /// </summary>
    [pbr::OriginalName("CS_LOGIN_REQ")] CsLoginReq = 1001,
    [pbr::OriginalName("SC_LOGIN_RES")] ScLoginRes = 1002,
    /// <summary>
    /// 1100-1199: Camp (动态营地创建与加入)
    /// </summary>
    [pbr::OriginalName("C2S_CREATE_CAMP_REQ")] C2SCreateCampReq = 1101,
    /// <summary>
    /// 创建结果
    /// </summary>
    [pbr::OriginalName("S2C_CREATE_CAMP_RES")] S2CCreateCampRes = 1102,
    /// <summary>
    /// 玩家请求加入营地
    /// </summary>
    [pbr::OriginalName("C2S_JOIN_CAMP_REQ")] C2SJoinCampReq = 1103,
    /// <summary>
    /// 加入结果
    /// </summary>
    [pbr::OriginalName("S2C_JOIN_CAMP_RES")] S2CJoinCampRes = 1104,
    /// <summary>
    /// 营地快照补帧
    /// </summary>
    [pbr::OriginalName("S2C_CAMP_SNAPSHOT")] S2CCampSnapshot = 1105,
    /// <summary>
    /// 玩家查询营地列表
    /// </summary>
    [pbr::OriginalName("C2S_QUERY_CAMP_LIST_REQ")] C2SQueryCampListReq = 1106,
    /// <summary>
    /// 营地列表响应
    /// </summary>
    [pbr::OriginalName("S2C_QUERY_CAMP_LIST_RES")] S2CQueryCampListRes = 1107,
    /// <summary>
    /// 2000-2999: Battle / Gameplay
    /// </summary>
    [pbr::OriginalName("CS_PING")] CsPing = 2001,
    [pbr::OriginalName("SC_PONG")] ScPong = 2002,
    [pbr::OriginalName("CS_MOVE_REQ")] CsMoveReq = 2003,
    [pbr::OriginalName("SC_MOVE_NTF")] ScMoveNtf = 2004,
    [pbr::OriginalName("SC_ENTER_VIEW")] ScEnterView = 2005,
    [pbr::OriginalName("SC_LEAVE_VIEW")] ScLeaveView = 2006,
    [pbr::OriginalName("CS_UPDATE_STATE_REQ")] CsUpdateStateReq = 2007,
    [pbr::OriginalName("SC_STATE_UPDATE_BATCH")] ScStateUpdateBatch = 2008,
    [pbr::OriginalName("SC_MOVE_NTF_BATCH")] ScMoveNtfBatch = 2009,
    [pbr::OriginalName("CS_SKILL_CAST_REQ")] CsSkillCastReq = 2010,
    [pbr::OriginalName("SC_DAMAGE_NTF")] ScDamageNtf = 2011,
    /// <summary>
    /// 3000-3999: Server-to-Server
    /// </summary>
    [pbr::OriginalName("SS_CREATE_ROOM_REQ")] SsCreateRoomReq = 3001,
    [pbr::OriginalName("SS_TERMINATE_ROOM_REQ")] SsTerminateRoomReq = 3002,
  }

  #endregion

}

#endregion Designer generated code
